# Generated by Django 5.1.1 on 2024-10-05 13:08

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='আমাদের সম্পর্কে', max_length=200)),
                ('heading', models.CharField(default='আমাদের সম্পর্কে', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='বিষয়বস্তু')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='ছবি')),
                ('url', models.URLField(blank=True, verbose_name='লিংক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('position', models.CharField(choices=[('top', 'শীর্ষে'), ('bottom', 'নীচে'), ('sidebar', 'সাইডবারে')], max_length=50, verbose_name='অবস্থান')),
            ],
            options={
                'verbose_name': 'বিজ্ঞাপন',
                'verbose_name_plural': 'বিজ্ঞাপনসমূহ',
            },
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(upload_to='carousel/')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='যোগাযোগ করুন', max_length=200)),
                ('heading', models.CharField(default='যোগাযোগ করুন', max_length=200)),
                ('submit_button_text', models.CharField(default='বার্তা পাঠান', max_length=50)),
                ('show_additional_info', models.BooleanField(default=True)),
                ('additional_info_title', models.CharField(default='অন্যান্য যোগাযোগের মাধ্যম', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('button_text', models.CharField(max_length=50)),
                ('button_url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(default='যোগাযোগ', max_length=100)),
                ('email_label', models.CharField(default='ইমেইল', max_length=100)),
                ('phone_label', models.CharField(default='ফোন', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('quick_links_title', models.CharField(default='দ্রুত লিঙ্ক', max_length=100)),
                ('social_media_title', models.CharField(default='সামাজিক মাধ্যম', max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Contents',
            },
        ),
        migrations.CreateModel(
            name='MarqueeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='জব পরীক্ষা প্ল্যাটফর্ম', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_images/')),
                ('navbar_title', models.CharField(default='জব পরীক্ষা প্ল্যাটফর্ম', max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_images/')),
                ('home_service_packages_title', models.CharField(default='আমাদের সার্ভিস প্যাকেজসমূহ', max_length=100)),
                ('home_featured_packages_title', models.CharField(default='ফিচার্ড প্যাকেজসমূহ', max_length=100)),
                ('home_testimonials_title', models.CharField(default='পরীক্ষার্থীদের মতামত', max_length=100)),
                ('home_faq_title', models.CharField(default='সাধারণ জিজ্ঞাসা', max_length=100)),
                ('home_dashboard_title', models.CharField(default='আপনার ড্যাশবোর্ড', max_length=100)),
                ('home_next_exam_title', models.CharField(default='পরবর্তী পরীক্ষা', max_length=100)),
                ('home_average_score_title', models.CharField(default='গড় স্কোর', max_length=100)),
                ('home_latest_result_title', models.CharField(default='সর্বশেষ পরীক্ষার ফলাফল', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('list', 'List')], max_length=10)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('order', models.IntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.aboutpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='button', to='core.aboutsection')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='core.contactpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='core.footercontent')),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['order'],
            },
        ),
    ]
