# Generated by Django 5.1.1 on 2024-10-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
