# Generated by Django 5.1.1 on 2024-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_menuitem_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিষয়বস্তু')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='ছবি')),
                ('url', models.URLField(blank=True, verbose_name='লিংক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('position', models.CharField(choices=[('top', 'শীর্ষে'), ('bottom', 'নীচে'), ('sidebar', 'সাইডবারে')], max_length=50, verbose_name='অবস্থান')),
            ],
            options={
                'verbose_name': 'বিজ্ঞাপন',
                'verbose_name_plural': 'বিজ্ঞাপনসমূহ',
            },
        ),
    ]
