# Generated by Django 5.1.1 on 2024-10-02 16:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='বিষয়বস্তু'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='contactadditionalinfo',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=200),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='marqueenotice',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
