# Generated by Django 5.1.1 on 2024-10-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aboutsection_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercontent',
            name='quick_links',
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='core.footercontent')),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['order'],
            },
        ),
    ]
