# Generated by Django 5.1.1 on 2024-10-02 16:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_free_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='comment',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
