# Generated by Django 5.1.1 on 2024-09-30 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveExam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveexam',
            name='exam_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 9, 30, 6, 25, 44, 262957, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveexam',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
