# Generated by Django 5.1.1 on 2024-10-05 13:09

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='বিবরণ')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='আইকন')),
            ],
            options={
                'verbose_name': 'ব্যাজ',
                'verbose_name_plural': 'ব্যাজসমূহ',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='বার্তা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'প্রতিক্রিয়া',
                'verbose_name_plural': 'প্রতিক্রিয়াসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100, verbose_name='কার্যক্রমের ধরন')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='বিবরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী কার্যক্রম',
                'verbose_name_plural': 'ব্যবহারকারী কার্যক্রমসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_layout', models.JSONField(default=dict, verbose_name='ড্যাশবোর্ড লেআউট')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী পছন্দ',
                'verbose_name_plural': 'ব্যবহারকারী পছন্দসমূহ',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=500, verbose_name='জীবনী')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='জন্ম তারিখ')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='অবস্থান')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='ওয়েবসাইট')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী প্রোফাইল',
                'verbose_name_plural': 'ব্যবহারকারী প্রোফাইলসমূহ',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='অর্জনের সময়')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী ব্যাজ',
                'verbose_name_plural': 'ব্যবহারকারী ব্যাজসমূহ',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
