# Generated by Django 5.1.1 on 2024-10-07 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={},
        ),
        migrations.AddField(
            model_name='userpreference',
            name='color_scheme',
            field=models.CharField(choices=[('light', 'হালকা'), ('dark', 'গাঢ়'), ('blue', 'নীল')], default='light', max_length=20, verbose_name='কালার স্কিম'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='widget_order',
            field=models.JSONField(default=list, verbose_name='উইজেট অর্ডার'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='dashboard_layout',
            field=models.CharField(choices=[('default', 'ডিফল্ট'), ('compact', 'কম্প্যাক্ট'), ('wide', 'প্রশস্ত')], default='default', max_length=20, verbose_name='ড্যাশবোর্ড লেআউট'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
