# Generated by Django 5.1.1 on 2024-09-28 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'ব্যাজ', 'verbose_name_plural': 'ব্যাজসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'প্রতিক্রিয়া', 'verbose_name_plural': 'প্রতিক্রিয়াসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'ব্যবহারকারী কার্যক্রম', 'verbose_name_plural': 'ব্যবহারকারী কার্যক্রমসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'verbose_name': 'ব্যবহারকারী ব্যাজ', 'verbose_name_plural': 'ব্যবহারকারী ব্যাজসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'ব্যবহারকারী পছন্দ', 'verbose_name_plural': 'ব্যবহারকারী পছন্দসমূহ'},
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(verbose_name='বিবরণ'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(upload_to='badges/', verbose_name='আইকন'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, verbose_name='নাম'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='বার্তা'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(max_length=100, verbose_name='কার্যক্রমের ধরন'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='description',
            field=models.TextField(verbose_name='বিবরণ'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='অর্জনের সময়'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='dashboard_layout',
            field=models.JSONField(default=dict, verbose_name='ড্যাশবোর্ড লেআউট'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='জীবনী')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='জন্ম তারিখ')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='অবস্থান')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='ওয়েবসাইট')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী প্রোফাইল',
                'verbose_name_plural': 'ব্যবহারকারী প্রোফাইলসমূহ',
            },
        ),
    ]
