# Generated by Django 5.1.1 on 2024-10-02 16:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_badge_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='বিবরণ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='বার্তা'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='বিবরণ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=500, verbose_name='জীবনী'),
        ),
    ]
