# Generated by Django 5.1.1 on 2024-10-05 13:09

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', django_ckeditor_5.fields.CKEditor5Field()),
                ('question_type', models.CharField(choices=[('MCQ', 'বহুনির্বাচনী'), ('TF', 'সত্য/মিথ্যা'), ('SA', 'সংক্ষিপ্ত উত্তর')], max_length=3)),
                ('correct_answer', django_ckeditor_5.fields.CKEditor5Field()),
                ('marks', models.FloatField(default=1.0)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'সহজ'), ('MEDIUM', 'মাঝারি'), ('HARD', 'কঠিন')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('exam_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.examcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('duration', models.DurationField()),
                ('total_marks', models.FloatField()),
                ('pass_marks', models.FloatField()),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.examcategory')),
                ('questions', models.ManyToManyField(to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('user_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.userexam')),
            ],
        ),
    ]
