# Generated by Django 5.1.1 on 2024-10-02 16:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcategory',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=555),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
