# Generated by Django 5.1.1 on 2024-10-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.userexam'),
            preserve_default=False,
        ),
    ]
