# Generated by Django 5.1.1 on 2024-10-01 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulednotification',
            name='notification_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('live_exam', 'লাইভ পরীক্ষা'), ('exam_schedule', 'পরীক্ষার সময়সূচি'), ('exam_result', 'পরীক্ষার ফলাফল'), ('blog_post', 'ব্লগ পোস্ট'), ('exam_registration', 'পরীক্ষা রেজিস্ট্রেশন'), ('book_purchase', 'বই ক্রয়'), ('general_info', 'সাধারণ তথ্য')], max_length=20),
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
        migrations.DeleteModel(
            name='ScheduledNotification',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
