# Generated by Django 5.1.1 on 2024-10-02 16:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_schedulednotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=255),
        ),
    ]
