# Generated by Django 5.1.1 on 2024-10-06 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_message_alter_notification_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('live_exam', 'লাইভ পরীক্ষা'), ('exam_result', 'পরীক্ষার ফলাফল'), ('blog_post', 'ব্লগ পোস্ট'), ('book_purchase', 'বই ক্রয়'), ('general_info', 'সাধারণ তথ্য'), ('upcoming_exam', 'আসন্ন পরীক্ষা'), ('login', 'লগইন'), ('package_purchase', 'প্যাকেজ ক্রয়')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('web', 'ওয়েব'), ('android', 'অ্যান্ড্রয়েড'), ('ios', 'আইওএস')], max_length=10)),
                ('device_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_exam', models.BooleanField(default=True)),
                ('exam_result', models.BooleanField(default=True)),
                ('blog_post', models.BooleanField(default=True)),
                ('book_purchase', models.BooleanField(default=True)),
                ('general_info', models.BooleanField(default=True)),
                ('upcoming_exam', models.BooleanField(default=True)),
                ('login', models.BooleanField(default=True)),
                ('package_purchase', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
